name: Main workflow

on:
  - pull_request
#  - push

jobs:
  build_and_test:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.05.x
          - 4.08.x
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: hamt.opam

      - run: opam install --deps-only --with-doc --with-test hamt

      - run: opam exec -- dune build --only-packages hamt

      - run: opam exec -- dune runtest
        # There is a known bug in ppx_expect < 0.14 on windows.
        # We can't have a fixed version before at least OCaml 4.07.
        if: ${{ ! (matrix.os == 'windows-latest' && matrix.ocaml-compiler == '4.05.x') }}

      - name: Build the bench suite
        # Only build it on latest ubuntu & OCaml, just to check obvious mistakes
        if: ${{ matrix.ocaml-compiler == '4.13.x' && matrix.os == 'ubuntu-latest' }}
        run: |
          opam pin add hamt-bench.dev . --no-action
          opam depext --yes hamt-bench
          opam install --deps-only hamt-bench
          opam exec -- dune build --only-packages hamt-bench
